# AI Agent Benchmark 测试配置文件

# 支持的测试级别
levels:
  - beginner
  - elementary 
  - intermediate
  - advanced
  - expert
  - master

# 支持的技术领域
domains:
  - web_development
  - mobile_app
  - algorithms
  - devops
  - data_science

# 基础配置
timeout: 300  # 每个任务的超时时间（秒）
parallel_tasks: 3  # 并行执行的任务数
sandbox_enabled: true  # 是否启用沙箱环境
output_formats:
  - json
  - html

# RAG Code Agent 配置
rag_agent:
  enabled: true
  max_iterations: 3
  code_extraction_patterns:
    - "```python"
    - "```javascript"
    - "```html"
    - "```css"
  timeout: 120  # RAG Agent 任务超时时间

# 评分标准配置
evaluation:
  beginner:
    functionality: 40     # 功能实现
    code_structure: 25    # 代码结构
    readability: 20       # 可读性
    edge_cases: 15        # 边界情况处理
    
  elementary:
    functionality: 35     # 功能实现
    code_quality: 25      # 代码质量
    user_experience: 20   # 用户体验
    error_handling: 20    # 错误处理
    
  intermediate:
    functionality: 30     # 功能实现
    architecture: 25      # 架构设计
    performance: 20       # 性能优化
    security: 15          # 安全性
    testing: 10           # 测试覆盖
    
  advanced:
    functionality: 25     # 功能实现
    architecture: 25      # 架构设计
    performance: 20       # 性能优化
    security: 15          # 安全性
    maintainability: 15   # 可维护性
    
  expert:
    innovation: 30        # 创新性
    architecture: 25      # 架构设计
    performance: 20       # 性能优化
    complexity: 15        # 复杂度处理
    knowledge: 10         # 领域知识
    
  master:
    innovation: 35        # 创新性
    architecture: 25      # 架构设计
    integration: 20       # 系统集成
    efficiency: 15        # 效率优化
    impact: 5             # 业务影响

# 日志配置
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/benchmark.log"

# 报告配置
reporting:
  include_code: true      # 是否在报告中包含生成的代码
  include_details: true   # 是否包含详细信息
  max_code_length: 5000   # 报告中代码的最大长度

# 执行配置
execution:
  timeout: 300  # 任务超时时间（秒）
  parallel_tasks: 3  # 并行执行的任务数
  sandbox_enabled: true  # 是否启用沙箱环境
  max_memory: "1GB"  # 最大内存使用
  max_disk: "100MB"  # 最大磁盘使用

# 输出配置
output:
  formats: ["json", "html"]  # 支持的报告格式
  detailed_logs: true  # 是否生成详细日志
  save_generated_code: true  # 是否保存生成的代码
  include_test_data: false  # 是否在报告中包含测试数据

# 测试环境配置
environment:
  python_version: "3.12"
  node_version: "18"
  rust_version: "1.70"
  docker_enabled: true
  
  # 允许的依赖包
  allowed_packages:
    python:
      - numpy
      - pandas
      - matplotlib
      - scikit-learn
      - flask
      - django
      - fastapi
      - requests
      - pytest
      - asyncio
    javascript:
      - react
      - express
      - axios
      - jest
      - webpack
    rust:
      - serde
      - tokio
      - wasm-bindgen

# 安全配置
security:
  disable_network: false  # 是否禁用网络访问
  disable_file_system: false  # 是否禁用文件系统访问
  allowed_file_extensions:
    - ".py"
    - ".js"
    - ".html"
    - ".css"
    - ".json"
    - ".yaml"
    - ".md"
    - ".rs"
    - ".toml"
  blocked_imports:
    - os.system
    - subprocess
    - exec
    - eval

# 性能基准
performance_benchmarks:
  beginner:
    max_execution_time: 10  # 秒
    max_memory_usage: 100  # MB
    max_lines_of_code: 100
    
  elementary:
    max_execution_time: 30  # 秒
    max_memory_usage: 200  # MB
    max_lines_of_code: 500
    
  intermediate:
    max_execution_time: 60  # 秒
    max_memory_usage: 500  # MB
    max_lines_of_code: 1000
    
  advanced:
    max_execution_time: 120  # 秒
    max_memory_usage: 1000  # MB
    max_lines_of_code: 2000
    
  expert:
    max_execution_time: 300  # 秒
    max_memory_usage: 2000  # MB
    max_lines_of_code: 5000
    
  master:
    max_execution_time: 600  # 秒
    max_memory_usage: 4000  # MB
    max_lines_of_code: 10000

# AI Agent接口配置
ai_agent:
  type: "openai"  # openai, anthropic, custom
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 4000
  timeout: 120
  retry_attempts: 3
  
  # 自定义提示模板
  prompt_template: |
    你是一个专业的编程助手。请根据以下任务描述生成高质量的代码解决方案。
    
    任务描述：
    {task_description}
    
    输入规范：
    {input_spec}
    
    输出规范：
    {output_spec}
    
    要求：
    1. 代码应该功能完整且正确
    2. 遵循最佳编程实践
    3. 包含适当的错误处理
    4. 代码应该易读易维护
    5. 如果可能，包含注释说明
    
    请直接提供代码解决方案： 